package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

/**
 * CourseLanguage generated by hbm2java
 */
public class CourseLanguage implements java.io.Serializable {

	private int idCourseLanguage;
	private Course course;
	private Language language;
	private Integer progressbarCourseLanguage;
	private String imgCourseLanguage;

	public CourseLanguage() {
	}

	public CourseLanguage(int idCourseLanguage) {
		this.idCourseLanguage = idCourseLanguage;
	}

	public CourseLanguage(int idCourseLanguage, Course course, Language language, Integer progressbarCourseLanguage,
			String imgCourseLanguage) {
		this.idCourseLanguage = idCourseLanguage;
		this.course = course;
		this.language = language;
		this.progressbarCourseLanguage = progressbarCourseLanguage;
		this.imgCourseLanguage = imgCourseLanguage;
	}

	public int getIdCourseLanguage() {
		return this.idCourseLanguage;
	}

	public void setIdCourseLanguage(int idCourseLanguage) {
		this.idCourseLanguage = idCourseLanguage;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public Integer getProgressbarCourseLanguage() {
		return this.progressbarCourseLanguage;
	}

	public void setProgressbarCourseLanguage(Integer progressbarCourseLanguage) {
		this.progressbarCourseLanguage = progressbarCourseLanguage;
	}

	public String getImgCourseLanguage() {
		return this.imgCourseLanguage;
	}

	public void setImgCourseLanguage(String imgCourseLanguage) {
		this.imgCourseLanguage = imgCourseLanguage;
	}

}
