package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private int idLanguage;
	private String nameLanguage;
	private Set studentLanguages = new HashSet(0);
	private Set courseLanguages = new HashSet(0);

	public Language() {
	}

	public Language(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public Language(int idLanguage, String nameLanguage, Set studentLanguages, Set courseLanguages) {
		this.idLanguage = idLanguage;
		this.nameLanguage = nameLanguage;
		this.studentLanguages = studentLanguages;
		this.courseLanguages = courseLanguages;
	}

	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

	public String getNameLanguage() {
		return this.nameLanguage;
	}

	public void setNameLanguage(String nameLanguage) {
		this.nameLanguage = nameLanguage;
	}

	public Set getStudentLanguages() {
		return this.studentLanguages;
	}

	public void setStudentLanguages(Set studentLanguages) {
		this.studentLanguages = studentLanguages;
	}

	public Set getCourseLanguages() {
		return this.courseLanguages;
	}

	public void setCourseLanguages(Set courseLanguages) {
		this.courseLanguages = courseLanguages;
	}

}
