package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private int idMission;
	private MissionLevel missionLevel;
	private MissionType missionType;
	private Recompense recompense;
	private String titleMission;
	private Integer scoreMission;
	private Character stateMission;
	private Character sendMission;
	private Date dateLimit;
	private Set courseMissions = new HashSet(0);
	private Set studentMissionHomeworks = new HashSet(0);

	public Mission() {
	}

	public Mission(int idMission) {
		this.idMission = idMission;
	}

	public Mission(int idMission, MissionLevel missionLevel, MissionType missionType, Recompense recompense,
			String titleMission, Integer scoreMission, Character stateMission, Character sendMission, Date dateLimit,
			Set courseMissions, Set studentMissionHomeworks) {
		this.idMission = idMission;
		this.missionLevel = missionLevel;
		this.missionType = missionType;
		this.recompense = recompense;
		this.titleMission = titleMission;
		this.scoreMission = scoreMission;
		this.stateMission = stateMission;
		this.sendMission = sendMission;
		this.dateLimit = dateLimit;
		this.courseMissions = courseMissions;
		this.studentMissionHomeworks = studentMissionHomeworks;
	}

	public int getIdMission() {
		return this.idMission;
	}

	public void setIdMission(int idMission) {
		this.idMission = idMission;
	}

	public MissionLevel getMissionLevel() {
		return this.missionLevel;
	}

	public void setMissionLevel(MissionLevel missionLevel) {
		this.missionLevel = missionLevel;
	}

	public MissionType getMissionType() {
		return this.missionType;
	}

	public void setMissionType(MissionType missionType) {
		this.missionType = missionType;
	}

	public Recompense getRecompense() {
		return this.recompense;
	}

	public void setRecompense(Recompense recompense) {
		this.recompense = recompense;
	}

	public String getTitleMission() {
		return this.titleMission;
	}

	public void setTitleMission(String titleMission) {
		this.titleMission = titleMission;
	}

	public Integer getScoreMission() {
		return this.scoreMission;
	}

	public void setScoreMission(Integer scoreMission) {
		this.scoreMission = scoreMission;
	}

	public Character getStateMission() {
		return this.stateMission;
	}

	public void setStateMission(Character stateMission) {
		this.stateMission = stateMission;
	}

	public Character getSendMission() {
		return this.sendMission;
	}

	public void setSendMission(Character sendMission) {
		this.sendMission = sendMission;
	}

	public Date getDateLimit() {
		return this.dateLimit;
	}

	public void setDateLimit(Date dateLimit) {
		this.dateLimit = dateLimit;
	}

	public Set getCourseMissions() {
		return this.courseMissions;
	}

	public void setCourseMissions(Set courseMissions) {
		this.courseMissions = courseMissions;
	}

	public Set getStudentMissionHomeworks() {
		return this.studentMissionHomeworks;
	}

	public void setStudentMissionHomeworks(Set studentMissionHomeworks) {
		this.studentMissionHomeworks = studentMissionHomeworks;
	}

}
