package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

/**
 * MissionState generated by hbm2java
 */
public class MissionState implements java.io.Serializable {

	private int idMissionState;
	private String nameMissionState;

	public MissionState() {
	}

	public MissionState(int idMissionState) {
		this.idMissionState = idMissionState;
	}

	public MissionState(int idMissionState, String nameMissionState) {
		this.idMissionState = idMissionState;
		this.nameMissionState = nameMissionState;
	}

	public int getIdMissionState() {
		return this.idMissionState;
	}

	public void setIdMissionState(int idMissionState) {
		this.idMissionState = idMissionState;
	}

	public String getNameMissionState() {
		return this.nameMissionState;
	}

	public void setNameMissionState(String nameMissionState) {
		this.nameMissionState = nameMissionState;
	}

}
