package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * MissionType generated by hbm2java
 */
public class MissionType implements java.io.Serializable {

	private int idMissionType;
	private String descripcionMissionType;
	private Set missions = new HashSet(0);

	public MissionType() {
	}

	public MissionType(int idMissionType) {
		this.idMissionType = idMissionType;
	}

	public MissionType(int idMissionType, String descripcionMissionType, Set missions) {
		this.idMissionType = idMissionType;
		this.descripcionMissionType = descripcionMissionType;
		this.missions = missions;
	}

	public int getIdMissionType() {
		return this.idMissionType;
	}

	public void setIdMissionType(int idMissionType) {
		this.idMissionType = idMissionType;
	}

	public String getDescripcionMissionType() {
		return this.descripcionMissionType;
	}

	public void setDescripcionMissionType(String descripcionMissionType) {
		this.descripcionMissionType = descripcionMissionType;
	}

	public Set getMissions() {
		return this.missions;
	}

	public void setMissions(Set missions) {
		this.missions = missions;
	}

}
