package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Recompense generated by hbm2java
 */
public class Recompense implements java.io.Serializable {

	private int idRecompense;
	private String titleRecompense;
	private String imgRecompense;
	private Integer scoreMin;
	private Set recompenseStudents = new HashSet(0);
	private Set missions = new HashSet(0);

	public Recompense() {
	}

	public Recompense(int idRecompense) {
		this.idRecompense = idRecompense;
	}

	public Recompense(int idRecompense, String titleRecompense, String imgRecompense, Integer scoreMin,
			Set recompenseStudents, Set missions) {
		this.idRecompense = idRecompense;
		this.titleRecompense = titleRecompense;
		this.imgRecompense = imgRecompense;
		this.scoreMin = scoreMin;
		this.recompenseStudents = recompenseStudents;
		this.missions = missions;
	}

	public int getIdRecompense() {
		return this.idRecompense;
	}

	public void setIdRecompense(int idRecompense) {
		this.idRecompense = idRecompense;
	}

	public String getTitleRecompense() {
		return this.titleRecompense;
	}

	public void setTitleRecompense(String titleRecompense) {
		this.titleRecompense = titleRecompense;
	}

	public String getImgRecompense() {
		return this.imgRecompense;
	}

	public void setImgRecompense(String imgRecompense) {
		this.imgRecompense = imgRecompense;
	}

	public Integer getScoreMin() {
		return this.scoreMin;
	}

	public void setScoreMin(Integer scoreMin) {
		this.scoreMin = scoreMin;
	}

	public Set getRecompenseStudents() {
		return this.recompenseStudents;
	}

	public void setRecompenseStudents(Set recompenseStudents) {
		this.recompenseStudents = recompenseStudents;
	}

	public Set getMissions() {
		return this.missions;
	}

	public void setMissions(Set missions) {
		this.missions = missions;
	}

}
