package co.edu.usbcali.modelo;
// Generated 15/07/2018 07:41:58 PM by Hibernate Tools 5.1.7.Final

/**
 * StudentMissionHomework generated by hbm2java
 */
public class StudentMissionHomework implements java.io.Serializable {

	private int idStudentMissionHomework;
	private Mission mission;
	private Student student;
	private String urlHomework;
	private String homeworkName;

	public StudentMissionHomework() {
	}

	public StudentMissionHomework(int idStudentMissionHomework) {
		this.idStudentMissionHomework = idStudentMissionHomework;
	}

	public StudentMissionHomework(int idStudentMissionHomework, Mission mission, Student student, String urlHomework,
			String homeworkName) {
		this.idStudentMissionHomework = idStudentMissionHomework;
		this.mission = mission;
		this.student = student;
		this.urlHomework = urlHomework;
		this.homeworkName = homeworkName;
	}

	public int getIdStudentMissionHomework() {
		return this.idStudentMissionHomework;
	}

	public void setIdStudentMissionHomework(int idStudentMissionHomework) {
		this.idStudentMissionHomework = idStudentMissionHomework;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getUrlHomework() {
		return this.urlHomework;
	}

	public void setUrlHomework(String urlHomework) {
		this.urlHomework = urlHomework;
	}

	public String getHomeworkName() {
		return this.homeworkName;
	}

	public void setHomeworkName(String homeworkName) {
		this.homeworkName = homeworkName;
	}

}
